title: Unapologetic Snippets
description: "Crazy Talk: My Disturbing Thoughts Wonâ€™t Go Away. What Do I Do?"
repository: igorlima/unapologetic-snippets # for github-metadata
theme: just-the-docs

aux_links:
  Github: https://github.com/igorlima/unapologetic-snippets

exclude:
  - my-env-jupyter/
  - docs/algorithms-data-structures/snippets/

include:
  - docs/algorithms-data-structures/snippets/index.md

nav_external_links:
  - title: Unapologetic Thoughts
    url: http://thoughts.ilima.xyz/
  - title: Just the Docs
    url: https://just-the-docs.github.io/just-the-docs/
